<a href="https://colab.research.google.com/github/AristotelesTN/MBA/blob/master/Untitled6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
import statsmodels.formula.api as sm
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.datasets.samples_generator import make_blobs, make_circles, make_moons, make_classification
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder
%matplotlib inline

In [0]:
df = pd.read_excel('Dataset_ISRA_Agosto_Set_19_Modificado.xlsx')

In [4]:
columns = ['Featureset: FS5D-ImageBlobber','QC Time','Glass Type','Idx','Optic', 'TBF','TDF','RBF','Faint','Moire','Row','Column',
          'Date and Time','Date','Time','Side','Bank','Type','Panel UUID','UUID','Mech. Center CW','Bank ID','Camera ID','Mech. Center DW',
          'Mech. B.Box Left','Mech. B.Box Top','Mat. Center CW','Mat. Center DW','Mat. B.Box Left','Mat. B.Box Top','Generator','Featureset UUID',
          'Class ID','Class name','Image Center CW','Image Center DW','Filename','is Unique?','File','Idx.1','Time.1','Defect UUID','Inspected',
          'Use for Statistics','Comment','Row Caption (for Autoformat)','Glass Thickness','Sensitivity Area','Quality Relevant','Reject',
          'Rule Number','New Type UUID','All Fulfilled Rules','User_Feature_47','User_Feature_48','User_Feature_49','User_Feature_50','User_Feature_51',
          'User_Feature_52','User_Feature_53','User_Feature_54','User_Feature_55','User_Feature_56','User_Feature_57','User_Feature_58','User_Feature_59',
          'User_Feature_60','User_Feature_61','User_Feature_62','User_Feature_63','Flow Position','Cross position']
df1 = df.drop(columns, axis=1)
print(len(columns))

72

In [67]:
df1.isnull().any()

Length QC Sheet        False
Net Width QC Sheet     False
Floatspeed m/min       False
Camera                 False
Width                  False
Length                 False
Area                   False
Diagonal               False
Type name              False
Type ID                False
Image B.Box Left       False
Image B.Box Top        False
Image B.Box Width      False
Image B.Box Length     False
Image Area             False
Image Diagonal         False
Channel                False
Resolution CW          False
Resolution DW          False
Flags                  False
No                     False
No 0                   False
Dist. Length BB        False
Dist. Width BB         False
Dist. Length Std       False
Dist. Width Std        False
Core Length            False
Core Width             False
Core Length 50%        False
Core Width 50%         False
                       ...
User_Feature_36        False
User_Feature_37        False
User_Feature_38        False
User_Feature_39        False
User_Feature_40        False
User_Feature_41        False
User_Feature_42        False
User_Feature_43        False
User_Feature_44        False
User_Feature_45        False
User_Feature_46        False
Height.1               False
Thickness.1            False
Speed                  False
Optic Length           False
Optic Width            False
Core Length.1          False
Core Width.1           False
Camera.1               False
Class                  False
Type.1                 False
Flow Pos [mm]          False
Cross Pos [mm]         False
QC Defect Type         False
Deformation Length      True
Deformation Width       True
Core Length.2           True
Core Width.2            True
Manual Defect Class     True
New Type\nV83e_f       False
Length: 588, dtype: bool

In [6]:
df1.dropna().head()

   Length QC Sheet  Net Width QC Sheet  ...  Manual Defect Class  New Type\nV83e_f
0           1100.1             3819.93  ...                  5.0         Top Speck
1           1100.1             3819.93  ...                  4.0            Bubble
2           1199.4             3825.02  ...                  3.0      Point Defect
3           1199.4             3825.02  ...                  2.0            Bubble
4           1199.4             3825.02  ...                  5.0             Stone

[5 rows x 588 columns]

In [7]:
df1.head(2)

   Length QC Sheet  Net Width QC Sheet  ...  Manual Defect Class  New Type\nV83e_f
0           1100.1             3819.93  ...                  5.0         Top Speck
1           1100.1             3819.93  ...                  4.0            Bubble

[2 rows x 588 columns]

In [8]:
df1.dtypes

Length QC Sheet        float64
Net Width QC Sheet     float64
Floatspeed m/min       float64
Camera                   int64
Width                  float64
Length                 float64
Area                   float64
Diagonal               float64
Type name               object
Type ID                 object
Image B.Box Left       float64
Image B.Box Top          int64
Image B.Box Width        int64
Image B.Box Length       int64
Image Area               int64
Image Diagonal         float64
Channel                  int64
Resolution CW          float64
Resolution DW          float64
Flags                    int64
No                       int64
No 0                     int64
Dist. Length BB        float64
Dist. Width BB         float64
Dist. Length Std       float64
Dist. Width Std        float64
Core Length            float64
Core Width             float64
Core Length 50%        float64
Core Width 50%         float64
                        ...
User_Feature_36        float64
User_Feature_37        float64
User_Feature_38        float64
User_Feature_39        float64
User_Feature_40        float64
User_Feature_41        float64
User_Feature_42        float64
User_Feature_43        float64
User_Feature_44        float64
User_Feature_45        float64
User_Feature_46        float64
Height.1               float64
Thickness.1            float64
Speed                  float64
Optic Length           float64
Optic Width            float64
Core Length.1          float64
Core Width.1           float64
Camera.1                 int64
Class                   object
Type.1                  object
Flow Pos [mm]          float64
Cross Pos [mm]         float64
QC Defect Type          object
Deformation Length     float64
Deformation Width      float64
Core Length.2           object
Core Width.2           float64
Manual Defect Class    float64
New Type\nV83e_f        object
Length: 588, dtype: object

In [9]:
df1.ndim

2

In [10]:
df1.size

259308

In [83]:
df1.shape

(441, 588)

In [0]:
df2 = df1

In [68]:
df2['QC Defect Type'].unique()

array(['Knot', 'Bubble', 'Stone', 'Tin', 'Top Tin', 'SO2 Dirt', 'Shell',
       'OPT_Type'], dtype=object)

In [16]:
df['Type.1'].unique()

array(['Top Speck', 'Bubble', 'Point Defect', 'Stone', 'Top Tin', 'Knot',
       'Artifact', 'Shell', 'Bottom Tin', 'Tin Oxide', 'Tin Stain',
       'Rollermark', 'Bubble (non Distorting)', 'Dirt'], dtype=object)

In [52]:
df2.replace(to_replace=['Not Founded', 'Top Tin'], value='Top Tin', inplace=True)
df2['QC Defect Type'].replace(to_replace=['knot', 'Knot'], value='Knot', inplace=True)
df2['QC Defect Type'].unique()

array(['Knot', 'Bubble', 'Stone', 'Tin', 'Top Tin', 'SO2 Dirt', 'Shell',
       'OPT_Type'], dtype=object)

In [195]:
dummies = pd.get_dummies(df2['Type.1'])
dummies.head()

   Artifact  Bottom Tin  Bubble  ...  Tin Stain  Top Speck  Top Tin
0         0           0       0  ...          0          1        0
1         0           0       1  ...          0          0        0
2         0           0       0  ...          0          0        0
3         0           0       1  ...          0          0        0
4         0           0       0  ...          0          0        0

[5 rows x 14 columns]

In [196]:
dict = dummies.to_dict(orient='records')
# DictVectorizer
from sklearn.feature_extraction import DictVectorizer
# instantiate a Dictvectorizer object for X
dv_X = DictVectorizer(sparse=False) 
# sparse = False makes the output is not a sparse matrix
# apply dv_X on X_dict
X_encoded = dv_X.fit_transform(dict)
# show X_encoded
X_encoded
# vocabulary
vocab = dv_X.vocabulary_
# show vocab
print(vocab)

Y = df2['Type.1'].replace(vocab)

{'Artifact': 0, 'Bottom Tin': 1, 'Bubble': 2, 'Bubble (non Distorting)': 3, 'Dirt': 4, 'Knot': 5, 'Point Defect': 6, 'Rollermark': 7, 'Shell': 8, 'Stone': 9, 'Tin Oxide': 10, 'Tin Stain': 11, 'Top Speck': 12, 'Top Tin': 13}

In [0]:
df2 = pd.concat([df2,dummies],axis=1)
df2 = pd.concat([df2,Y.rename('Type_Y')],axis=1)

In [0]:
cor = df2.corr()

In [155]:
#Correlation with output variable
cor_target = abs(cor['Knot'])
#Selecting highly correlated features
relevant_features = cor_target[cor_target>0.4]
relevant_features.dropna()

                                    Knot      Knot  ...      Knot      Knot
Image B.Box Length              0.439291  0.439291  ...  0.439291  0.439291
Image Diagonal                  0.435045  0.435045  ...  0.435045  0.435045
Faint.Mean Sub Blob Area [pix]  0.434932  0.434932  ...  0.434932  0.434932
Knot                            1.000000  1.000000  ...  1.000000  1.000000
Knot                            1.000000  1.000000  ...  1.000000  1.000000
Knot                            1.000000  1.000000  ...  1.000000  1.000000
Knot                            1.000000  1.000000  ...  1.000000  1.000000
Knot                            1.000000  1.000000  ...  1.000000  1.000000
Knot                            1.000000  1.000000  ...  1.000000  1.000000
Knot                            1.000000  1.000000  ...  1.000000  1.000000
Knot                            1.000000  1.000000  ...  1.000000  1.000000

[11 rows x 8 columns]

In [271]:
X = df2[df2.columns[1:569]]._get_numeric_data()
temp = df2.loc[:, ~df2.columns.duplicated()]
temp.head()
Y = temp['Type_Y']

X[X==np.inf]=np.nan
X.fillna(X.mean(), inplace=True)

Y[Y==np.inf]=np.nan
Y.fillna(13.0, inplace=True)

print(X.shape)
print(Y.shape)

(441, 566)
(441,)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py:8682: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)
/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2882: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  exec(code_obj, self.user_global_ns, self.user_ns)
/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py:6130: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)

In [272]:
 
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=42)

print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(308, 566) (308,)
(133, 566) (133,)

In [273]:
knn = KNeighborsClassifier(n_neighbors=13, p=2)
knn.fit(x_train, y_train.ravel())

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=13, p=2,
                     weights='uniform')

In [274]:
list_res = []
for p in [1, 2]:
    knn.p = p
    
    for k in range(1, 10, 2):
        knn.n_neighbors = k
        y_pred = knn.predict(x_test)
        acc = accuracy_score(y_test, y_pred)*100
        list_res.append([k, 'l1_distance' if p == 1 else 'l2_distance', acc])
        
pdf = pd.DataFrame(list_res, columns=['k', 'dist. func.', 'acurácia'])
pdf

   k  dist. func.   acurácia
0  1  l1_distance  44.360902
1  3  l1_distance  50.375940
2  5  l1_distance  53.383459
3  7  l1_distance  54.887218
4  9  l1_distance  48.872180
5  1  l2_distance  44.360902
6  3  l2_distance  50.375940
7  5  l2_distance  53.383459
8  7  l2_distance  54.887218
9  9  l2_distance  48.872180

In [294]:
clf_sk = GaussianNB()
clf_sk.fit(x_train, y_train.ravel())

print(clf_sk.theta_)
print(clf_sk.sigma_)
print(clf_sk.predict(x_test))
print(clf_sk.predict_proba(x_test))

[[4.05000000e+03 1.15700000e+01 3.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 2.70000000e-01]
 [3.81820750e+03 7.92250000e+00 7.50000000e-01 ... 0.00000000e+00
  0.00000000e+00 7.35000000e-01]
 [3.81901533e+03 8.12694611e+00 1.95209581e+00 ... 1.53754491e+00
  8.64730539e-01 7.76167665e-01]
 ...
 [3.85381000e+03 5.71666667e+00 2.33333333e+00 ... 8.00000000e-02
  1.30000000e-01 7.03333333e-01]
 [3.85239000e+03 6.54000000e+00 1.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 7.50000000e-01]
 [3.83448336e+03 6.20059352e+00 1.77461402e+00 ... 5.99807644e-01
  5.17620855e-01 5.72370286e-01]]
[[9.48414703e+12 9.48414703e+12 9.48414703e+12 ... 9.48414703e+12
  9.48414703e+12 9.48414703e+12]
 [9.48414703e+12 9.48414703e+12 9.48414703e+12 ... 9.48414703e+12
  9.48414703e+12 9.48414703e+12]
 [9.48414703e+12 9.48414703e+12 9.48414703e+12 ... 9.48414703e+12
  9.48414703e+12 9.48414703e+12]
 ...
 [9.48414703e+12 9.48414703e+12 9.48414703e+12 ... 9.48414703e+12
  9.48414703e+12 9.48414703e+12]
 [9.48414703e+12 9.48414703e+12 9.48414703e+12 ... 9.48414703e+12
  9.48414703e+12 9.48414703e+12]
 [9.48414703e+12 9.48414703e+12 9.48414703e+12 ... 9.48414703e+12
  9.48414703e+12 9.48414703e+12]]
[ 8.  2. 13.  8.  2.  2.  2.  5.  2.  2.  2.  2.  2.  5. 13.  2.  2.  2.
 13.  5.  2.  2.  2.  3.  2.  2.  2.  2.  2.  2.  2.  6.  2.  2.  2.  4.
  2.  2.  6.  2.  6.  5.  5.  2.  2.  2.  6.  4.  3.  2.  2.  5.  2.  9.
  2.  2.  9.  5.  2.  3. 13.  2.  2.  9.  2.  2.  4.  2.  2.  2.  2.  2.
  6.  2. 11. 11.  5.  5.  2.  6. 13.  4.  2.  7.  2.  2.  4.  2.  2.  2.
  2.  7.  6. 11.  7.  2.  2.  6.  5.  2.  9.  2. 11.  2.  6.  2.  2.  2.
  3. 13.  2.  5.  2.  2.  2.  2.  2.  9.  3.  2.  2.  2.  2. 13.  7. 11.
  2.  6. 13.  2.  2.  2.  2.]
[[0.00000000e+00 1.51541996e-03 1.46399197e-03 ... 3.63701118e-09
  0.00000000e+00 4.89234898e-03]
 [0.00000000e+00 1.11530290e-02 4.72275495e-01 ... 3.12838546e-02
  0.00000000e+00 6.33564036e-03]
 [0.00000000e+00 5.11898456e-11 7.11388733e-02 ... 8.49236821e-19
  0.00000000e+00 5.43359674e-01]
 ...
 [0.00000000e+00 1.05087701e-05 8.43778758e-01 ... 8.91322000e-10
  0.00000000e+00 1.36133056e-02]
 [0.00000000e+00 8.58095202e-02 5.59607031e-01 ... 2.95133873e-02
  0.00000000e+00 4.14013963e-02]
 [0.00000000e+00 9.41466525e-06 8.04770063e-01 ... 6.39386084e-10
  0.00000000e+00 7.29506521e-03]]